### ISSUE TITLE
Wont load on start.

### ISSUE THREAD

**Issue by SwishMasters** [JCulley/ProQuests-Documentation#113]
```
[20:36:12 WARN]: org.apache.commons.lang.UnhandledException: Plugin ProQuests v2.0.4.1 generated an exception while executing task 13
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Entity.hasPermission(Ljava/lang/String;)Z
        at com.culleystudios.proquests.players.PlayerPermission.eligible(PlayerPermission.java:90)
        at com.culleystudios.proquests.listeners.PlayerJoin$2.run(PlayerJoin.java:97)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by JCulley** [comment]
The CraftBukkit 1.7 is not supported as it does not include the hasPermission() function as stated by this error. Next time please follow the guidelines ([https://github.com/JCulley/ProQuests-Documentaion/wiki/Error-Guidelines](url)).
