### ISSUE TITLE
Cant get the plugin to run, for some time now

### ISSUE THREAD

**Issue by gerardvanschip** [JCulley/ProQuests-Documentation#142]
- git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- ProQuests v2.0.4.6

2 errors below, one when a player logs on and one when you run the /proquest command. I did a fresh restart to ensure nothing else was causing a problem.

**Log on error:**
>[12:47:37] [Craft Scheduler Thread - 7/WARN]: [ProQuests] Plugin ProQuests v2.0.4.6 generated an exception while executing task 3155
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_65]
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_65]
	at java.util.AbstractCollection.addAll(Unknown Source) ~[?:1.8.0_65]
	at com.culleystudios.proquests.players.QPlayer.executeActions(QPlayer.java:277) ~[ProQuests.jar:?]
	at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:177) ~[ProQuests.jar:?]
	at com.culleystudios.proquests.util.QuestUtil.checkActiveQuests(QuestUtil.java:292) ~[ProQuests.jar:?]
	at com.culleystudios.proquests.listeners.PlayerJoin$2.run(PlayerJoin.java:73) ~[ProQuests.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_65]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]

**Run command error:**
>[12:49:15] [Server thread/INFO]: KaizenWorlds issued server command: /proquest
[12:49:58] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to ProQuests v2.0.4.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319) [custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257) [custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [custom.jar:git-Spigot-b6ecf3b-fb423b8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_65]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_65]
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_65]
	at java.util.AbstractCollection.addAll(Unknown Source) ~[?:1.8.0_65]
	at com.culleystudios.proquests.players.QPlayer.executeActions(QPlayer.java:277) ~[?:?]
	at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:177) ~[?:?]
	at com.culleystudios.proquests.util.EligibilityUtil.isEligble(EligibilityUtil.java:82) ~[?:?]
	at com.culleystudios.proquests.quests.internal.ChatQuest.onChat(ChatQuest.java:175) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[custom.jar:git-Spigot-b6ecf3b-fb423b8]
	... 11 more

**Comment by JCulley** [comment]
Follow the guidelines please and provided your Spigot account or I will have to close the issue.

**Comment by JCulley** [comment]
Closing as it’s been 3 days with no updates.
