### ISSUE TITLE
Console Error with all Quests

### ISSUE THREAD

**Issue by LandonEZ** [JCulley/ProQuests-Documentation#173]
Spigot Account : https://www.spigotmc.org/members/rebelcraft.141340/
Spigot Version : TacoSpigot 1.8.8
ProQuest Version : 2.0.7
Problem : An error pops up in the Console and quests start FREAKING out
Example 1 : /quest doesnt work
Example 2 : /creator doesn't work

https://pastebin.com/2Xk3UGA0

**Comment by JCulley** [comment]
The error is stating the plugin is attempting to execute null actions. This means somewhere in your configuration you have an error with actions. It appears as though the exception is being thrown from a break quest complete actions which can be read from the stack trace. 

`Caused by: java.lang.NullPointerException
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[custom.jar:git-TacoSpigot-fd3209f3]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) ~[custom.jar:git-TacoSpigot-fd3209f3]
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339) ~[custom.jar:git-TacoSpigot-fd3209f3]
    at com.culleystudios.proquests.util.Actions.runAction(Actions.java:174) ~[ProQuests.jar:?]
    at com.culleystudios.proquests.util.Actions.executeAction(Actions.java:199) ~[ProQuests.jar:?]
    at com.culleystudios.proquests.util.Actions.executeActions(Actions.java:208) ~[ProQuests.jar:?]
    at com.culleystudios.proquests.players.QPlayer.executeActions(QPlayer.java:51) ~[ProQuests.jar:?]
    at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:50) ~[ProQuests.jar:?]
    at com.culleystudios.proquests.quests.internal.BreakQuest.onBreak(BreakQuest.java:109) ~[ProQuests.jar:?]`

So review your files and ensure you're using valid actions.
