### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by x2088** [JCulley/ProQuests-Documentation#175]
[09:02:53 INFO]: [ProQuests] Successfully hooked into world_guard
[09:02:53 ERROR]: Error occurred while enabling ProQuests v2.0.7 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.culleystudios.proquests.listeners.PlayerChat@5d2c4b35 while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:522) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at com.culleystudios.proquests.ProQuests.loadListeners(ProQuests.java:77) ~[?:?]
        at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by JCulley** [comment]
Hey,

This does not follow the guidelines so please update them to comply so I can actually investigate the situation. In addition please provide a more detailed explanation as you labeled this as a MySQL error however the error has nothing to do with MySQL.

Thanks.

**Comment by JCulley** [comment]
Almost 2 weeks without additional information, closing.
