### ISSUE TITLE
I want to ask if this is wrong?

### ISSUE THREAD

**Issue by HoneyBearc** [JCulley/ProQuests-Documentation#184]
[09:38:39 WARN]: [ProQuests-Packages] Task #1188 for ProQuests-Packages v2.0.2 generated an exception
java.lang.NoSuchMethodError: com.culleystudios.proquests.managers.MenuManager.reload()V
        at com.culleystudios.proquests.packages.PQPackages$1.run(PQPackages.java:73) ~[ProQuests-Packages.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[09:38:42 INFO]: [ProQuests] Unable to locate any npcs to load...

**Comment by JCulley** [comment]
Use the template if you want to open an issue.

**Comment by HoneyBearc** [comment]
Sorry, I don't understand the meaning.
