### ISSUE TITLE
1.13.1 Support [Beta Plugin]

### ISSUE THREAD

**Issue by NFRCG** [JCulley/ProQuests-Documentation#189]
**Details**
The current public beta version of this plugin should be bumped to 1.13.1. I realize this is not a "true issue", but also noticed how there was a similar issue opened by yourself for 1.13 support. I would personally appreciate it if we could have an update (not even an ETA) on bumping the newest version to 1.13.1, much like that issue. Even so much as labels added to the issue. 

**Additional Information**
I can provide my required information if need be, but I am not sure how relevant it is to this report. 
Issue I am referring to is found here: https://github.com/JCulley/ProQuests-Documentation/issues/182

Thanks again!

**Comment by JCulley** [comment]
Compatibility updates don’t need to be requested, they are released on my schedule. No there is no ETA. Haven’t even looked at 1.13.1 to be completely honest so not even sure if any changes need to be made.

**Comment by gerardvanschip** [comment]
The Spigot team has stopped dev for 1.13 as it was too buggy, they focus on 1.13.1 now which will soon take over from 1.12 as the official build.

Ever since they moved to 1.13.1 my server has been running smoothly.

[13:23:37] [Server thread/INFO]: [ProQuests] Enabling ProQuests v2.1.0.1-beta
[13:23:37] [Server thread/INFO]: [ProQuests] You are using an unsupported server version, disabling...
[13:23:37] [Server thread/INFO]: [ProQuests] Disabling ProQuests v2.1.0.1-beta
[13:23:37] [Server thread/ERROR]: Error occurred while disabling ProQuests v2.1.0.1-beta (Is it up to date?)
java.lang.NullPointerException: null
	at com.culleystudios.proquests.ProQuests.onDisable(ProQuests.java:127) ~[ProQuests.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-145a37a-3123a06]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363) [spigot.jar:git-Spigot-145a37a-3123a06]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot.jar:git-Spigot-145a37a-3123a06]
	at com.culleystudios.proquests.ProQuests.setupCompatability(ProQuests.java:307) [ProQuests.jar:?]
	at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:94) [ProQuests.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-145a37a-3123a06]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-145a37a-3123a06]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-145a37a-3123a06]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:428) [spigot.jar:git-Spigot-145a37a-3123a06]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:342) [spigot.jar:git-Spigot-145a37a-3123a06]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot.jar:git-Spigot-145a37a-3123a06]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot.jar:git-Spigot-145a37a-3123a06]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot.jar:git-Spigot-145a37a-3123a06]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [spigot.jar:git-Spigot-145a37a-3123a06]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-145a37a-3123a06]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[13:23:37] [Server thread/INFO]: [ProQuests] Running build #32463

**Comment by JCulley** [comment]
As I previously stated I work on my own schedule and do not give estimates as to when I plan on having new versions out. As can be seen by this suggestion it is still listed as a suggestion because I have not even started work on 1.13.1 compatability. I don’t know why you attached a stacktrace stating the plugin disabled using 1.13.1 because as I have stated 1.13.1 support has not even been looked at yet.

**Comment by gerardvanschip** [comment]
I thought that might help in the debugging process. For when your schedule includes 1.13.1 you will have bug reports here for you waiting.

**Comment by JCulley** [comment]
1.13.1 Support has been integrated and will be in the next release. Like the previous version this is a beta and has not been tested.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-1-give-players-objectives.18249/update?update=246256
