### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#201]
**Spigot Account**
Provide a direct clickable link to your user profile.

**Spigot account** - https://www.spigotmc.org/members/alex_5678.438771/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).

**Plugin version** - 2.0.7.1 and 2.1.0.1-beta
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.

**Spigot Version** - git-Spigot-2086bb0-1988d7f (MC: 1.12.2)
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.

**Link to log file** - The complete Log file will not be postet due to privacy rules. You can contact me for further information

[15:31:36] [Server thread/INFO]: [ProQuests] Loading ProQuests v2.0.7.1
[15:31:54] [Server thread/INFO]: [ProQuests] Enabling ProQuests v2.0.7.1
[15:31:54] [Server thread/INFO]: [ProQuests] Running build #438771
[15:31:54] [Server thread/WARN]: 	at com.culleystudios.proquests.database.MySQLConnection.createTables(MySQLConnection.java:100)
[15:31:54] [Server thread/WARN]: 	at com.culleystudios.proquests.database.MySQLConnection.<init>(MySQLConnection.java:54)
[15:31:54] [Server thread/WARN]: 	at com.culleystudios.proquests.ProQuests.loadFiles(ProQuests.java:166)
[15:31:54] [Server thread/WARN]: 	at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:96)
[15:31:54] [Server thread/INFO]: [ProQuests] Unable to connect to a MySQL database, disabling plugin...
[15:31:54] [Server thread/INFO]: [ProQuests] Disabling ProQuests v2.0.7.1
[15:31:54] [Server thread/ERROR]: Error occurred while disabling ProQuests v2.0.7.1 (Is it up to date?)
	at com.culleystudios.proquests.ProQuests.onDisable(ProQuests.java:126) ~[?:?]
	at com.culleystudios.proquests.database.MySQLConnection.<init>(MySQLConnection.java:60) [ProQuests2_0_7_1.jar:?]
	at com.culleystudios.proquests.ProQuests.loadFiles(ProQuests.java:166) [ProQuests2_0_7_1.jar:?]
	at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:96) [ProQuests2_0_7_1.jar:?]
[15:31:54] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[15:31:54] [Server thread/INFO]: [ProQuests] Loading external plugin hooks....
[15:31:54] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[15:31:54] [Server thread/ERROR]: Error occurred while enabling ProQuests v2.0.7.1 (Is it up to date?)
	at com.culleystudios.proquests.plugins.PluginHookType.<clinit>(PluginHookType.java:81) ~[?:?]
	at com.culleystudios.proquests.ProQuests.loadHooks(ProQuests.java:182) ~[?:?]
	at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:97) ~[?:?]
[15:33:12] [Server thread/INFO]: alex_5678 issued server command: /proquests
org.bukkit.command.CommandException: Cannot execute command 'proquests' in plugin ProQuests v2.0.7.1 - plugin is disabled.

<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.

**Additional information** - Issue happens every time on start on both versions
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**

**Additional media** - none
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
“[15:31:54] [Server thread/INFO]: [ProQuests] Unable to connect to a MySQL database, disabling plugin...”

The plugin is telling you the exact issue so I don’t know why you opened an issue for this. Either configure a MySQL connection in the config or install SQLite. One or the other is clearly listed as a required dependency for the plugin to run.

**Comment by ghost** [comment]
That doesn't seem to be the Problem. SQL was configured.

With SQLite this happens:
[16:29:41] [Server thread/INFO]: [ProQuests] Loading ProQuests v2.1.0.1-beta
[16:29:57] [Server thread/INFO]: [ProQuests] Enabling ProQuests v2.1.0.1-beta
[16:29:57] [Server thread/INFO]: [ProQuests] Running build #438771
[16:29:57] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[16:29:57] [Server thread/INFO]: [ProQuests] Loading external plugin hooks....
[16:29:57] [Server thread/INFO]: [ProQuests] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[16:29:57] [Server thread/ERROR]: Error occurred while enabling ProQuests v2.1.0.1-beta (Is it up to date?)
	at com.culleystudios.proquests.plugins.PluginHookType.<clinit>(PluginHookType.java:81) ~[?:?]
	at com.culleystudios.proquests.ProQuests.loadHooks(ProQuests.java:183) ~[?:?]
	at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:98) ~[?:?]

**Comment by JCulley** [comment]
Feel free to provide the full log file as I can’t gleam anything useful from what you’re providing me. It’s obviously a hook not registering properly but I can’t tell you which one.

**Comment by ghost** [comment]
https://pastebin.com/FtHqFqwC

The deleted lines should not be important to the issue but most of them mustn't be posted.

**Comment by JCulley** [comment]
“com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs”

So referring to my previous statement this is clearly a MySQL issue. Your database is not configured to allow for large VARCHAR datasets and you will have to change it.

**Comment by ghost** [comment]
Did you use a table with collation of utf-8?
please give more information about the required sql database on spigot.
is latin1_general_cs ok or will it cause any trouble?

**Comment by JCulley** [comment]
You can check the table yourself using “SHOW TABLE STATUS”. No collation is explicitly defined when creating the table.

**Comment by ghost** [comment]
the question was not wich collation the table has.

the question was which it needs.
I figured out that it doesn't work with utf8 (which is used by default if no other os explicitly given)
The table creation works with latin1_general_cs and I just want you to tell me wether it will work with this or not.

or better: when you test the plugin with your own sql: wich collation is used by your sql-database?

**Comment by JCulley** [comment]
“Did you use a table with collation of utf-8?”

Your question as seen above is clearly asking which collation was used, so as I stated there is not one explicitly defined.

There is no defined answer as to which it needs as the answer is there is no specific requirement. You can modify the table as you wish as long as the columns and table names stay in tact and can hold the expected value types. It will work with UTF-8 however you need to manually change any columns to accommodate larger values ie. change it to TEXT, BLOB or whatever.

It is your responsibility to manage your database as you wish, ProQuests simply initializes the tables and columns it needs.
