### ISSUE TITLE
Have a pb with your plugins please help me

### ISSUE THREAD

**Issue by N3ox13** [JCulley/ProQuests-Documentation#211]
Hi, i have a pb with your plugin you can help me ? i have a full last version plugins 

Ty

Could not pass event BlockBreakEvent to ProQuests v2.1.0.2-beta
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:123) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1165) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-2440e18-4228a56]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-2440e18-4228a56]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
	at com.culleystudios.proquests.util.EligibilityUtil.isEligble(EligibilityUtil.java:120) ~[?:?]
	at com.culleystudios.proquests.quests.internal.BreakQuest.onBreak(BreakQuest.java:445) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-2440e18-4228a56]
	... 17 more
[03:27:45] [Server thread/ERROR]: Could not pass event BlockBreakEvent to ProQuests v2.1.0.2-beta
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:123) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1165) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-2440e18-4228a56]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-2440e18-4228a56]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
	at com.culleystudios.proquests.util.EligibilityUtil.isEligble(EligibilityUtil.java:120) ~[?:?]
	at com.culleystudios.proquests.quests.internal.BreakQuest.onBreak(BreakQuest.java:445) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-2440e18-4228a56]
	... 17 more

**Comment by JCulley** [comment]
Update the title to be more descriptive and follow the guidelines or I will have to close this issue.

**Comment by JCulley** [comment]
Closed due to PayPal dispute.
