### ISSUE TITLE
Startup exception WorldGuard hook

### ISSUE THREAD

**Issue by scuffi** [JCulley/ProQuests-Documentation#217]
**Spigot account** - https://www.spigotmc.org/members/captaina.91398/
<br>

**Plugin version** - v2.1.1.1
<br>

**Spigot Version** - git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
<br>

**Link to log file** - https://pastebin.com/gm7YqSSX
<br>

**Additional information** - When I type /quests, /proquests, /creator, nothing happens, no error in console (as seen in log) no message printed in chat. It has something to do with a version mismatch but I just downloaded it off the SpigotMC site a couple minutes ago. Also, config hasn't been touched or anything. Freshly added the plugin for the first time. Vault is also latest version.
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
> no error in console (as seen in log)

`[19:55:28] [Server thread/ERROR]: Error occurred while enabling ProQuests v2.1.1.1 (Is it up to date?)
java.lang.NullPointerException
    at com.culleystudios.proquests.plugins.PluginHookType.getHook(PluginHookType.java:123) ~[?:?]
    at com.culleystudios.proquests.ProQuests.loadHooks(ProQuests.java:188) ~[?:?]
    at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:99) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

Pretty sure that's an error, but your not a buyer so this is going to be closed.

**Comment by JCulley** [comment]
> no error in console (as seen in log)

`[19:55:28] [Server thread/ERROR]: Error occurred while enabling ProQuests v2.1.1.1 (Is it up to date?)
java.lang.NullPointerException
    at com.culleystudios.proquests.plugins.PluginHookType.getHook(PluginHookType.java:123) ~[?:?]
    at com.culleystudios.proquests.ProQuests.loadHooks(ProQuests.java:188) ~[?:?]
    at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:99) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

Pretty sure this is an exception. My best guess is due to the fact you don't have WorldGuard and I hadn't tested without it so its checking for the dependancy when it doesn't exist.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-13-2-25-off-holiday-sale-give-players-objectives.18249/update?update=254155
