### ISSUE TITLE
PlaceholderAPI using outdated version

### ISSUE THREAD

**Issue by JTGgamer** [JCulley/ProQuests-Documentation#225]
**Spigot account** - JTGgamer (https://www.spigotmc.org/members/jtggamer.173903/)

<br>

**Plugin version** - 2.1.1.2

<br>

**Spigot Version** - Spigot 1.13.1

<br>

**Link to log file** - No errors, nothing happens. (https://hastebin.com/ojiluqugax.bash)

<br>

**Steps to reproduce:**
1. Install And Download
2. Restart The Server
3. No React To Any Commands From The Plugin.

**Additional information** - 
When you type a command, auto complete does show that the commands exist, but when they are sent they don't do anything at all. It is shown to be running with no errors.

<br>

**Additional media** - 

![image](https://user-images.githubusercontent.com/27565081/49828195-22baa300-fd83-11e8-862b-50d4465ae885.png)

![image](https://user-images.githubusercontent.com/27565081/49828213-2ea66500-fd83-11e8-954f-ce26bfc20012.png)

**Comment by JCulley** [comment]
Please provide your log file.

**Comment by JTGgamer** [comment]
[latest.log](https://github.com/JCulley/ProQuests-Documentation/files/2669349/latest.log)

**Comment by JCulley** [comment]
> [20:31:29] [Server thread/ERROR]: Error occurred while enabling ProQuests v2.1.1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderHook
	at com.culleystudios.proquests.plugins.PluginHookType.<clinit>(PluginHookType.java:89) ~[?:?]
	at com.culleystudios.proquests.ProQuests.loadHooks(ProQuests.java:187) ~[?:?]
	at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:99) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.PlaceholderHook
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_172]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172]
	... 14 more

As can be clearly seen from your log file you are using an unsupported version of PlaceholderAPI

**Comment by JTGgamer** [comment]
Thanks
