### ISSUE TITLE
Placeholder API outdated version

### ISSUE THREAD

**Issue by Arrandirs** [JCulley/ProQuests-Documentation#231]
[13:31:25] [Server thread/ERROR]: Error occurred while enabling ProQuests v2.1.1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderHook
	at com.culleystudios.proquests.plugins.PluginHookType.<clinit>(PluginHookType.java:89) ~[?:?]
	at com.culleystudios.proquests.ProQuests.loadHooks(ProQuests.java:187) ~[?:?]
	at com.culleystudios.proquests.ProQuests.onEnable(ProQuests.java:99) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.PlaceholderHook
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 14 more

I don't know why i don't want to load but i try all versions and i have tryed to read the issues to found any error :/ thx :)

**Comment by JCulley** [comment]
This does not follow any of the guidelines. Regardless if you took a moment and read even the first couple of lines of the error you would have your answer.

> java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderHook

Also this was also answered here: 
https://github.com/JCulley/ProQuests-Documentation/issues/225

If you don’t adhere to the guidelines in the future any requests you open will not receive a response. Also please attempt to solve the problem yourself before reaching out for further assistance as it takes time away from me being able to fix actual bugs and/or errors.

**Comment by JCulley** [comment]
This does not follow any of the guidelines. Regardless if you took a moment and read even the first couple of lines of the error you would have your answer.

> java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderHook

Also this was also answered here:
