### ISSUE TITLE
/quest [18:36:20] [Server thread/ERROR]: null

### ISSUE THREAD

**Issue by xXjojojXx** [JCulley/ProQuests-Documentation#256]
STOOKAA issued server command: /quest
[18:36:20] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'quest' in plugin ProQuests v2.1.1.3.1 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-0f708cb]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by xXjojojXx** [comment]
/ plugin turns red ProQuests please help as soon as possible

**Comment by JCulley** [comment]
This doesn’t follow the guidelines at all. You have provided next to no information revelvant for me to investigate any potential “issues” so I’m closing this issue.
