### ISSUE TITLE
ClassNotFound Exception - Messages API

### ISSUE THREAD

**Issue by ghost** [JCulley/ProQuests-Documentation#325]
**Spigot Account**
Provide a direct clickable link to your user profile.
> Example: https://www.spigotmc.org/members/1

**Spigot account** - https://www.spigotmc.org/members/cm_lectric.232281/
<br>

**Plugin Version**
Provide the ProQuests version you are running (support is only provided for the latest version).
> Example: 2.0.7.1

**Plugin version** - 2.1.1.14
<br>

**Spigot Version**
Provide the Spigot version you are using (as stated in startup). If you are using a fork such as PaperSpigot this should also be noted here.
> Example: git-Spigot-93e20b3-f8500c0 (MC: 1.12.2)

**Spigot Version** - 1.8.8
<br>

**Log File**
Provide a clickable url to a plain text website (https://pastebin.com, https://hastebin.com) with your **ENTIRE LOG FILE** this includes from startup to now. Partial log files or specific errors you deem "relevant" will not be accepted.
> Example: https://hastebin.com/iyugokawux.cpp

**Link to log file** - https://pastebin.com/nz5fVm4S
<br>

**Addition Information**
Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question, and if in reference to an external plugin hook the version of the hooked plugin.
> Example:
> After reloading the plugin a quest created using the in-game creator does not load properly and is throwing errors in console. Upon investigating the produced quest file it appears it is being saved improperly with invalid formatting. All changes to the quest have been made using the in-game creator
> 
> Steps to reproduce:
> 1. Use the plain text quest file referenced below and put them in your quests folder
> 2. Attempt to reload the plugin using /proquests reload
> 3. Notice that numerous errors are thrown and they don't load properly

**Additional information** - Whenever I break blocks with a tokenenchanted item, an error spams the console. Along with this, although I can't document it with a log error, a bunch of placeholder quests triggered for a player on my server even though he didn't actually have a placeholder value that would complete the quests. He only broke 12k blocks, but quests completed for him in which the requirements were in the billions. Again, I don't have much to show for this but I'm thinking this bug might have caused enough lag to mess up the placeholder quest.
<br>

**Additional Media**
Provide any configuration files, links to images, or videos which better explain the "error" you are encountering. **All provided media must be accessible online, download links will not be accepted**
> Example: This link provided contains the configuration for the quest causing the error https://hastebin.com/iyugokawux.cpp

**Additional media** - {insert here}
<br>

**Please keep issues relevant to the "error" in question and try to refrain from opening more than (1) issue per day**

**Comment by JCulley** [comment]
> Along with this, although I can't document it with a log error, a bunch of placeholder quests triggered for a player on my server even though he didn't actually have a placeholder value that would complete the quests

> Provide as much additional information explaining the issue. This can include but is not limited to an explanation of the "error", the steps to produce/reproduce the "error" in question

I can’t investigate what can not be clearly explained/documented.

**Comment by AtomixCM** [comment]
[03:51:03] [Server thread/ERROR]: Could not pass event TEBlockExplodeEvent to ProQuests v2.1.1.14
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at com.vk2gpz.tokenenchant.potions.ExplosivePotion$b.run(ExplosivePotion$b.java:406) [TE-ExplosiveEnchant%20(4).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoClassDefFoundError: com/culleystudios/propackages/util/Messages
	at com.culleystudios.proquests.players.QPlayer.executeActions(QPlayer.java:281) ~[?:?]
	at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:183) ~[?:?]
	at com.culleystudios.proquests.quests.external.TokenEnchantBreakQuest.onBreak(TokenEnchantBreakQuest.java:512) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor983.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	... 11 more
[03:51:03] [Server thread/ERROR]: Could not pass event TEBlockExplodeEvent to ProQuests v2.1.1.14
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at com.vk2gpz.tokenenchant.potions.ExplosivePotion$b.run(ExplosivePotion$b.java:406) [TE-ExplosiveEnchant%20(4).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoClassDefFoundError: com/culleystudios/propackages/util/Messages
	at com.culleystudios.proquests.players.QPlayer.executeActions(QPlayer.java:281) ~[?:?]
	at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:183) ~[?:?]
	at com.culleystudios.proquests.quests.external.TokenEnchantBreakQuest.onBreak(TokenEnchantBreakQuest.java:512) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor983.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	... 11 more
[03:51:03] [Server thread/ERROR]: Could not pass event TEBlockExplodeEvent to ProQuests v2.1.1.14
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at com.vk2gpz.tokenenchant.potions.ExplosivePotion$b.run(ExplosivePotion$b.java:406) [TE-ExplosiveEnchant%20(4).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoClassDefFoundError: com/culleystudios/propackages/util/Messages
	at com.culleystudios.proquests.players.QPlayer.executeActions(QPlayer.java:281) ~[?:?]
	at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:183) ~[?:?]
	at com.culleystudios.proquests.quests.external.TokenEnchantBreakQuest.onBreak(TokenEnchantBreakQuest.java:512) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor983.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	... 11 more
[03:51:03] [Server thread/ERROR]: Could not pass event TEBlockExplodeEvent to ProQuests v2.1.1.14
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at com.vk2gpz.tokenenchant.potions.ExplosivePotion$b.run(ExplosivePotion$b.java:406) [TE-ExplosiveEnchant%20(4).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoClassDefFoundError: com/culleystudios/propackages/util/Messages
	at com.culleystudios.proquests.players.QPlayer.executeActions(QPlayer.java:281) ~[?:?]
	at com.culleystudios.proquests.util.QuestUtil.completeEvents(QuestUtil.java:183) ~[?:?]
	at com.culleystudios.proquests.quests.external.TokenEnchantBreakQuest.onBreak(TokenEnchantBreakQuest.java:512) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor983.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	... 11 more
[03:51:03] [Server thread/INFO]: [Tokens] Added 75000 tokens to OfficialLegendry.
[03:51:03] [Server thread/INFO]: [Tokens] Added 50000 tokens to OfficialLegendry.
[03:51:03] [Server thread/INFO]: [Tokens] Added 5000000 tokens to OfficialLegendry.
[03:51:03] [Server thread/INFO]: Permission "deluxetags.tag.blocklegend" added!
[03:51:03] [Server thread/INFO]: Permission "deluxetags.tag.blockexpert" added!
[03:51:03] [Server thread/INFO]: [Tokens] Added 250000 tokens to OfficialLegendry.
[03:51:03] [Server thread/INFO]: Permission "deluxetags.tag.blockdominator" added!
[03:51:03] [Server thread/INFO]: [Tokens] Added 25000 tokens to OfficialLegendry.
[03:51:03] [Server thread/INFO]: Permission "deluxetags.tag.blockpro" added!
[03:51:03] [Server thread/INFO]: [Tokens] Added 1000000 tokens to OfficialLegendry.
[03:51:03] [Server thread/INFO]: Permission "deluxetags.tag.blockdevastator" added!
[03:51:03] [Server thread/INFO]: Permission "deluxetags.tag.blockmaster" added!
[03:51:03] [Server thread/INFO]: [Tokens] Added 2500000 tokens to OfficialLegendry.
[03:51:03] [Server thread/INFO]: Permission "deluxetags.tag.annihilator" added!
[03:51:04] [Server thread/INFO]: OfficialLegendry issued server command: /sell
[03:51:16] [Server thread/INFO]: <OfficialLegendry> lol what

**Comment by ghost** [comment]
https://pastebin.com/AdrFM89w
Here is the bit where the player got all of the quests completed.

Attached is the entire log
[2019-10-03-1 (1).log](https://github.com/JCulley/ProQuests-Documentation/files/3684647/2019-10-03-1.1.log)

**Comment by JCulley** [comment]
> I can’t investigate what can not be clearly explained/documented.

Sending me a unrelated ClassNotFound exception as the reason for a players quests ultimately being completed (without actually meeting the requirements? Who knows I’m still guessing as to what this is even about) is not a sufficient explanation.

I’ll look into the ClassNotFound exception but that’s the extent of it. Do your own RCA and provide a detailed description of this other “issue” with a clear explanation and steps to reproduce if a consistent error exists. Only if you can do so should you open another ticket.

**Comment by JCulley** [comment]
https://www.spigotmc.org/resources/proquests-1-7-1-14-give-players-objectives.18249/update?update=304027
