### ISSUE TITLE
ProQuests "PLACEHOLDER_QUEST " bug

### ISSUE THREAD

**Issue by yeshangyo** [JCulley/ProQuests-Documentation#92]
`[01:44:14 ERROR]: Could not pass event QuestUpdateEvent to ProQuests v2.0.3.5
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        at com.culleystudios.proquests.ProQuests$1.run(ProQuests.java:317) [ProQuests.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) [PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.culleystudios.proquests.quests.internal.PlaceholderQuest.onPlaceholder(PlaceholderQuest.java:406) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor573.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-1.11.2-b1104-nether2.jar:git-Paper-1104]
        ... 11 more
 `

quest config:

> type: PLACEHOLDER_QUEST
> start_values: true
> required_placeholders:
> - '%player_level%;1.0'

**Comment by JCulley** [comment]
Does not follow guidelines.

**Comment by shanklm** [comment]
你能看懂就可以。。
